name: Dev CI

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.ps1'
  workflow_dispatch:
    branches:
      - dev

jobs:

  build:
    if: "!contains(github.event.head_commit.message, '*** NO_CI ***')"
    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest

    env:
      Source_Directory: .\src
      Solution_Name: BMSSV.IO.sln
      Project_Directory: .\src\BMSSV.IO
      Project_Path: src\BMSSV.IO\BMSSV.IO.csproj
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET 6.0.x workload
    - name: Install .NET 6.0.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    # Update Project Assembly Information
    - name: Update Project Assembly Information
      id: updateNfo_BMSSV_IO
      shell: powershell
      run: 
        $prevVer = `
          .\UpdateCSProjAssyVer.ps1 `
            -CSProjPath:"${{ env.Project_Path }}" `
            -Silent `
            -GetVersion;
        echo "::set-output name=prevVersion::$prevVer"; `
        .\UpdateCSProjAssyVer.ps1 `
          -CSProjPath:"${{ env.Project_Path }}" `
          -Authors:"Zach `"KhaosVoid`" Tommey" `
          -Product:"BMSSV.IO" `
          -Description:"An IO library for interacting with the Mercury Steam BMSSV save format." `
          -Copyright:"Zach `"KhaosVoid`" Tommey - Copyright" `
          -AppendCopyrightYear; `
        $curVer = `
          .\UpdateCSProjAssyVer.ps1 `
            -CSProjPath:"${{ env.Project_Path }}" `
            -Silent `
            -GetVersion;
        echo "::set-output name=currentVersion::$curVer"

    # Restore
    - name: Restore
      working-directory: ${{ env.Source_Directory }}
      run: dotnet restore --nologo --verbosity quiet

    # Build
    - name: Build
      working-directory: ${{ env.Source_Directory }}
      run: dotnet build --configuration $env:Configuration --no-restore --nologo --verbosity quiet
      env:
        Configuration: ${{ matrix.configuration }}

    # Test
    - name: Test
      working-directory: ${{ env.Source_Directory }}
      run: dotnet test --no-restore --nologo --verbosity quiet

    # Commit Updated Assembly Information (NO_CI)
    - name: Commit Updated Assembly Information *** NO_CI ***
      shell: powershell
      run:
        $previousVer = "${{ steps.updateNfo_BMSSV_IO.outputs.prevVersion }}"; `
        $currentVer = "${{ steps.updateNfo_BMSSV_IO.outputs.currentVersion }}"; `
        $commitMessage = "*** NO_CI *** Updated Assembly Info "; `
        if ($previousVer -eq "0.0.0.0") { $commitMessage += "([$currentVer])" } `
        else { $commitMessage += "([$previousVer] => [$currentVer])" } `
        git config user.name github-actions; `
        git config user.email github-actions@github.com; `
        git add .; `
        git commit -m "$commitMessage"; `
        git push